name: Kyom Theme Deployment

on:
  push:
    branches:
      - master

jobs:

  deploy:
    if: contains(github.ref, 'master') && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://takahashifumiki.com
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install NPM
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Build Package
        run: bash bin/build.sh refs/tags/${{ github.sha }}

      - name: Deploy to Server
        env:
          DEPLOY_KEY: ${{ secrets.ID_RSA_FUMIKI_VPS_SAKURA }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H fumiki.sakura.ne.jp >> ~/.ssh/known_hosts
          rsync -rptv --checksum --delete \
            -e "ssh -i ~/.ssh/deploy_key" \
            ./ fumiki@fumiki.sakura.ne.jp:/home/fumiki/www/main/wp-content/themes/kyom/
