name: Kyom Theme Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        php: [ '8.2', '8.3' ] # PHP versions to check.
        wp: [ 'latest', '6.6' ]      # WordPress version to check.
    uses: tarosky/workflows/.github/workflows/wp-unit-test.yml@main
    with:
      php_version: ${{ matrix.php }}
      wp_version: ${{ matrix.wp }}

  phpcs:
    name: PHP Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run test suite
        run: composer lint

  assets:
    name: Test Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install NPM
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install NPM Dependencies
        run: npm install

      - name: Lint Assets
        run: npm run lint:js

      - name: Check build really succeeds
        run: npm run package

  status:
    name: Status Check
    needs: [ phpcs, assets, test ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
